"use client";
import './globals.css'
import { Inter } from 'next/font/google'
import Script from 'next/script'
import { SessionProvider } from 'next-auth/react'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Micro - Bondis en Argentina',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-[#202020]">
      <Script src="https://kit.fontawesome.com/e80c9c3cc8.js" />
      <body className={inter.className}>
        <SessionProvider>
        {children}
        </SessionProvider>
      </body>
    </html>
  )
}
